"""
	enum: OPERATION_CODE
	The codes of each operation
	--- Code
		LOGIN = 1
		READ = 2
		UPDATE = 3
		NEW = 4
		DELETE = 5
		CONVERSION = 6
		FORMAT = 7
		LOGOUT = 8
		GETVERSION = 9
		SELECT = 10
		SUBROUTINE = 11
		EXECUTE = 12
		DICTIONARIES = 13
		LKSCHEMAS = 14
		LKPROPERTIES = 15
		GETTABLE = 16
		RESETCOMMONBLOCKS = 17
		UPDATEPARTIAL = 18
		COMMAND_XML = 150
		COMMAND_JSON = 151
	---
"""
class OPERATION_CODE:
	LOGIN = 1
	READ = 2
	UPDATE = 3
	NEW = 4
	DELETE = 5
	CONVERSION = 6
	FORMAT = 7
	LOGOUT = 8
	GETVERSION = 9
	SELECT = 10
	SUBROUTINE = 11
	EXECUTE = 12
	DICTIONARIES = 13
	LKSCHEMAS = 14
	LKPROPERTIES = 15
	GETTABLE = 16
	RESETCOMMONBLOCKS = 17
	UPDATEPARTIAL = 18
	COMMAND_XML = 150
	COMMAND_JSON = 151
